# Site settings
author: Kristina Frederick
title: Fresh Cup O' JavaScript
header-img: img/home-bg.png
email: kristinafrederick@icloud.com
copyright_name: Kristina Frederick
description: > # this means to ignore newlines until "baseurl:"
  A Journey of Ruby and the (Software Engineering) Beast
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  k-frederick

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
